server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://203.195.138.136:3306/mall?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: cm970903


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml